ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE PLUGGABLE DATABASE PDBCLONE
  FROM PDBSRC@pdbsrc_link
  FILE_NAME_CONVERT = (
    'C:\app\oracle\oradata\CDB1\PDBSRC',
    'C:\app\oracle\oradata\CDB2\PDBCLONE'
  );

ALTER PLUGGABLE DATABASE PDBCLONE OPEN;

EXIT;
