name: Release ZIP

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          zip -r oracle19c-pdb-migration-lab.zip . -x "*.git*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: oracle19c-pdb-migration-lab.zip
